### ISSUE TITLE
Freeze after wifi drop

### ISSUE THREAD

**Issue by Navarro11** [dddomodossola/remi#253]
Hello,

at first I have to say this project is really awesome and I love it!

Unfortunatelly I have one problem. If I open web page on mobile phone and then disable wifi on phone, server hangs and is impossible to open web page from another device.

> remi.server      INFO     Started httpserver http://127.0.0.1:8081/
remi.request     INFO     Authenticating
192.168.0.59 - - [02/Dec/2018 22:35:59] "GET / HTTP/1.1" 401 -
remi.request     INFO     built UI (path=/)
remi.request     DEBUG    get: /
192.168.0.59 - - [02/Dec/2018 22:35:59] "GET / HTTP/1.1" 200 -
remi.server.ws   INFO     connection established: ('192.168.0.59', 52236)
remi.server.ws   DEBUG    handle
remi.server.ws   DEBUG    handshake
remi.server.ws   INFO     handshake complete
remi.server.ws   DEBUG    send_message: 0306000353... -> ('192.168.0.59', 52236)
remi.server.ws   DEBUG    send_message: 3... -> ('192.168.0.59', 52236)
remi.server.ws   DEBUG    on_message: connected
remi.server.ws   DEBUG    send_message: 3... -> ('192.168.0.59', 52236)
remi.server.ws   DEBUG    on_message: callback
remi.request     DEBUG    App.onload event occurred
remi.server.ws   DEBUG    send_message: 3... -> ('192.168.0.59', 52236)
remi.server.ws   DEBUG    on_message: callback
remi.request     DEBUG    App.onpageshow event occurred
remi.server.ws   DEBUG    send_message: 1306009182... -> ('192.168.0.59', 52236)
remi.request     DEBUG    get: /favicon.ico
remi.request     DEBUG    get: /favicon.ico
remi.server.ws   DEBUG    send_message: 1306009182... -> ('192.168.0.59', 52236)
remi.server.ws   DEBUG    send_message: 1306009182... -> ('192.168.0.59', 52236)
remi.server.ws   DEBUG    send_message: 1306009182... -> ('192.168.0.59', 52236)
remi.server.ws   DEBUG    send_message: 1306009182... -> ('192.168.0.59', 52236)

Somewhere here I disable wifi on phone.

> remi.server.ws   DEBUG    send_message: 1306009182... -> ('192.168.0.59', 52236)
remi.server.ws   DEBUG    send_message: 1306009182... -> ('192.168.0.59', 52236)
remi.server.ws   DEBUG    send_message: 1306009182... -> ('192.168.0.59', 52236)
remi.server.ws   DEBUG    send_message: 1306009182... -> ('192.168.0.59', 52236)

At this point it hangs forever. Sometimes if I reenable wifi on phone, this line shows up and then server acts normally.

> remi.server.ws   DEBUG    ws ending websocket service

What can be wrong?

Thank you.

**Comment by dddomodossola** [comment]
Hello @Navarro11 , thank you for reporting. Which version are you using? Can you show here your script?

**Comment by Navarro11** [comment]
Hello,

I'm using last stable version installed via pip.

Script:
[main.txt](https://github.com/dddomodossola/remi/files/2637505/main.txt)

**Comment by dddomodossola** [comment]
I will be unable to debug this for about 3 days. Can you please make a test with one of the examples? does it happen the same with them? check that the parameter multiple_instances have to be the same, change it in the example to meet the value of your script

**Comment by Navarro11** [comment]
I've tried widgets_overview_app.py and it is same. After some time after wifi drop on mobile phone, webpage is not accessible from any device.

**Comment by dddomodossola** [comment]
@Navarro11 you found an important bug in this version. I will debug and prepare a fix in some days. Waiting for the fix you can use the previous version 1.2.2 .

**Comment by dddomodossola** [comment]
@Navarro11 I pushed a possible fix on master branch. Can you please install it directly from GitHub (not pypi) and let me know if this fixes the problem?

**Comment by Navarro11** [comment]
@dddomodossola  I'm really sorry but this didn't help. Behaviour after disconnecting phone is the same.

**Comment by dddomodossola** [comment]
@Navarro11 thank you for the test. 

Can you please confirm me you updated your remi version with the following command? 
`pip install git+https://github.com/dddomodossola/remi.git`

Furthermore, with python version are you using?

**Comment by dddomodossola** [comment]
@Navarro11 I will do some additional test and provide you a solution ;-)

**Comment by Navarro11** [comment]
Hello @dddomodossola, I thought wifi router is the problem, but I tried connect via hotspot on mobile phone and the behaviour is still the same. I created hotspot on phone and connect raspberry and pc to it. Via ssh on phone I ran script on raspberry. I opened webpage on pc and after while I blocked pc on hotspot, so pc was force disconnected. After that webpage opened on phone stopped updating and refresh was not successful. Then I tried cancel script on ssh via ctrl+c, but there popped up some error message in server.py that "endpoint is not connected" or something like this, and script was not cancelled so I had to restart ssh.

**Comment by dddomodossola** [comment]
@Navarro11 thank you a lot for helping me investigating on this problem. Which command you executed to start the script? have you used **nohup**?

**Comment by Navarro11** [comment]
I run script simply **python3 main.py**.

**Comment by Navarro11** [comment]
@dddomodossola  Of course I know this :). This is not the problem. I wrote it because when any device is not force disconnected, script can be canceled by ctrl+c without problem, but after force disconnect, script is not canceled so I think script is hanging somewhere and therefore webpage stops work. I will make video this afternoon with pc and phone screen to better undestand :).

**Comment by dddomodossola** [comment]
@Navarro11 I mean that, if you don't use nohup, after wifi disconnection, it could happen that the remi script becames not reachable, because the server gets stopped. however ok, from the video I can better understand.

**Comment by Navarro11** [comment]
@dddomodossola  Here is the video [https://www.youtube.com/watch?v=mIIFnodReM0](url). There are few subtitles, I hope it will help.

**Comment by nzjrs** [comment]
@dddomodossola this smells like long socket timeout (windows? or another library  messing with sys.setsockettimeout) combined with remi pinging connected clients in a loop, which means that one blocking client can hang the server.

**Comment by dddomodossola** [comment]
@Navarro11 thank you for the great video. 
@nzjrs that's possible, maybe the long socket timeout blocks the thead lock.
I need to test it further

**Comment by dddomodossola** [comment]
@Navarro11 @nzjrs I was able to reproduce the problem. It is caused exactly as @nzjrs says. A long socket timeout freezes the application. The most common situation happens when a client reconnects to the server, and that should be fixed now. You can test it @Navarro11 , now it should work for you.

However I plan to remake the websocket implementation to make it nonblocking.

**Comment by dddomodossola** [comment]
@Navarro11 I doubt it could be caused by your raspberrypi. I will do some additional tests soon. Thank you for your collaboration ;-)

**Comment by batzkass** [comment]
Hi Davide,

I'm currently running remi==2019.11, and I confirm that this bug is present in this version. Each time one of the connected clients has a connection break, the server totally hangs a few seconds later. I say "a few seconds" but after some investigations I realized that its not related to time (like a timeout), but rather to the amount of message sent (or received, I don't really know).

I planed to send you more precise information and test results on Thursday. However before that -- as my remi version is almost 1 year old -- I would like to know if there is any chance that you already solved the issue in new versions ?

Many thanks.

**Comment by dddomodossola** [comment]
@batzkass I don't know. Can you please end me an example script to reproduce the problem?

**Comment by batzkass** [comment]
Sure, on thursday. It should rather be a list of steps to reproduce based
on your example scripts rather than a simple script.

Le mar. 6 oct. 2020 à 18:26, Davide Rosa <notifications@github.com> a
écrit :

**Comment by batzkass** [comment]
Hi,

I finally found some time to work on that today. I had to write a tiny script which basically shows a series of 2000 random integers, and changes the 2000 values with an idle function every 0.2s (see http://kneib.fr/helloworld_app.py). I use the last remi version available on pypi.

I made a video of the bug here: https://www.youtube.com/watch?v=_Ep8PV37xmk

On my PC, I launch the server and I use firefox to connect to it. Then I use my phone to connect on the server though wifi (video streaming from my phone is done through usb). Here everything is fine, ints are updating.
I then brutally cut off the wifi from my phone and then after a few seconds the server freezes forever (the 2000 integers are not updated anymore, and no new connections are possible). I also tried to connect my phone to the server before my pc and the result is the same. Note that, once freezed, the first ctrl+c command will show something in the log, then after that nothing more happens (need to kill the process).

You may wonder why I put 2000 ints and not just 1. This is because I realized that the time it takes between the wifi shut down and the server freeze highly depends on the amount of data sent during this period. In fact I think that the server rather freezes after a certain amount of data sent from the server though the websocket. For example, in the video, it takes about 8s, but when I put 1000 ints I get about 15s, and so on.

To my understanding, remi can't deal with websockets that are brutally not responding. Like if a sending buffer was slowly filled until it is totally full. I had to use the wifi trick to reproduce a real connection failure, as killing (with SIGKILL on linux) a browser makes the OS to gently close the websocket and remi is happy with that.

In fact this issue haunts me since I use remi (few years) as sometimes the client PCs are connected through 3G/4G, or experience wifi drops. For me it was just "remi server crashes sometimes, its not very stable", but I just found this issue on gitlab now and decided to further investigate.

Don't hesitate to tell me if I can help for debugging.
Many thanks for remi and for your help.

**Comment by dddomodossola** [comment]
@batzkass I tried your script different times but I can't reproduce the problem. However from your video I can see a "broken pipe" error caused by the forced disconnection. I see that after wifi disconnection the messages continue to be spawn on console, and so I suppose it is not caused by a long socket timeout. Maybe we just need to catch the broken pipe error. 
I will test it on a linux machine to reproduce the problem and hopefully fix.

**Comment by batzkass** [comment]
Well, linux could be the common point with @Navarro11 who was running the server on a raspberry, so probably on raspbian.
The "broken pipe" error occurs when I press ctrl-c, I think this specific error may rightly be caused by ctrl-c. To my opinion it is rather that the server tries to send messages to a disconnected client, hence progressively fills in its sending buffer. If I'm right with this scenario, maybe the solution could be to close the connection for clients that doesn't acknowledge the messages after a certain time.

**Comment by dddomodossola** [comment]
@batzkass this could be a good solution, I will test on raspbian today ;-)

**Comment by batzkass** [comment]
I tried to set a timeout of 10 here https://github.com/dddomodossola/remi/blob/3f96dd0e8efb6d61d6d66a6b2b7f66ab1407ced7/remi/server.py#L141
And the issue doesn't appear... but each connection is resetted every 10s, producing a glich for the client.

**Comment by batzkass** [comment]
Well I found a kind of fix by encapsulating the send request in a thread. This way the server continues to send data to other clients. This is the new send_message function : 

    def send_message(self, message):
        if not self.handshake_done:
            self._log.warning("ignoring message %s (handshake not done)" % message[:10])
            return

        self._log.debug('send_message: %s... -> %s' % (message[:10], self.client_address))
        out = bytearray()
        out.append(129)
        length = len(message)
        if length <= 125:
            out.append(length)
        elif 126 <= length <= 65535:
            out.append(126)
            out += struct.pack('>H', length)
        else:
            out.append(127)
            out += struct.pack('>Q', length)
        if not pyLessThan3:
            message = message.encode('utf-8')
        out = out + message
        
        class sendThread(threading.Thread):
            def __init__(self,msg,req):
                threading.Thread.__init__(self)
                self.msg=msg
                self.req=req
            def run(self):
                self.req.send(self.msg)
        st=sendThread(out,self.request)
        st.start()

**Comment by batzkass** [comment]
If you wish to keep this fix, it would be nice to gently close the websocket after a certain time of thread execution to avoid plenty of "broken pipe" errors in the terminal and useless messages sent to nobody (if the client finally reconnects, all messages that haven't been actually sent will return a "broken pipe" error, after that the server is back to normal).

**Comment by batzkass** [comment]
Also, (I'll try to stop here :-P), I think that websockets for each client should be treated in a different thread to limit this kind of bugs to propagate to everyone. But this may need some time to code it, and it requires to implement some inter-processes communications (tell each worker that they must send, gather the client answers ...).

**Comment by dddomodossola** [comment]
@batzkass Yesterday I reproduced the error with a raspberrypi. It seems that the blocking socket communication is preventing the mutex to be released and so that specific instance of application is blocked. The server is still available for new clients if the parameter *multiple_instances=True*. This is important to understand that all clients in remi are Threaded.
It is not required to create additional threads.
The problem cause:
- Remi tries to send an update to a died client;
- The socket send command is executed correctly, no error is returned
- Remi is not aware about the died client and sends updates up to the size of an internal socket buffer
- After this, the blocking send command doesn't return and so stops the client update, that is inside a mutexed function calling tree
- The mutex is not released
- All other clients of the same app instance are blocked.

The solution, is to check the socket functionality before to send a message. I should use the socket.select function. Today I will try to provide a solution.  ;-)

Thank you a lot for the collaboration

**Comment by dddomodossola** [comment]
@batzkass You can find the bugfix in a branch called *bugfix_253*. Please try that version and eventually confirm it works.

**Comment by batzkass** [comment]
Thanks, I'll check it next week.

Le ven. 9 oct. 2020 à 22:34, Davide Rosa <notifications@github.com> a
écrit :

**Comment by batzkass** [comment]
Hi @dddomodossola , it seems not to work. Once I get the `Exception: Websocket is not writable`, the server no longer sends messages to other clients. I think that raising without a try/catch is too strong, I would rather do:
```
if not writable:
    try:
        raise ...
   except:
        return
```
as suggested here : https://docs.python.org/3/tutorial/errors.html#raising-exceptions

**Comment by batzkass** [comment]
Or even 
```
if not writable:
    self._log.debug("Websocket is not writable")
    return
self.request.sendall(out)
```
seems to work. The drawback is that after the log message occurs, the server can't be closed by ctrl+c or ctrl+d anymore. Do you know if there is a timeout somewhere to close the websocket on the server-side ? Anyway, if the client experienced a connection drop and never reconnects, it seems better to close the websocket somewhere. And as this error occurs only after some buffer is full, I would even do: 
```
if not writable:
    self._log.debug("Websocket is not writable")
    CLOSE THE CONNECTION HERE
self.request.sendall(out)
```

**Comment by dddomodossola** [comment]
@batzkass Thank you a lot for the help, I will try this night to fix this ;-)

**Comment by dddomodossola** [comment]
@batzkass I updated the branch **bugfix_253** please look and test the updated version. I tested it intensively on linux and it work well. I hope it works on Mac also. ;-)

**Comment by dddomodossola** [comment]
@batzkass Can you please test and report the result?

**Comment by batzkass** [comment]
Sorry, I'm AFK these days. But for that bug I'll do an exception :-)
So, bad news it still doesn't work for me. Which version of linux do you use for your tests ? I'm on ubuntu 19.10, python 3.7.5.
I get your new error message, but after that it hangs :
```
remi.server.ws   DEBUG    send_message: 1140087270... -> ('127.0.0.1', 33772)
remi.server.ws   DEBUG    send_message: 1140087270... -> ('192.168.1.26', 60348)
remi.request     DEBUG    removing websocket instance, communication error with client
```
I checked and the issue is with `ws.close(...)` that hangs as `self.request.sendall(...)` did. It seems that it can't close the connection with an "unresponding" client for some versions of  linux or python or the server lib...

**Comment by dddomodossola** [comment]
@batzkass Thank you again for the patience :-D . I have to further investigate.

**Comment by dddomodossola** [comment]
@batzkass Now it should be fixed. I reproduced the error on ubuntu 18 and fixed it. Can you test it?

**Comment by batzkass** [comment]
Yes, I confirm that it is fixed. Many thanks Davide.

**Comment by dddomodossola** [comment]
@batzkass Thank you so much for supporting in debug and tests. ;-)
